all:
	cd classic && make
	cd advanced && make
	cd error && make
	cd ansi-care && make
	cd robust && make
	cd g++ && make
clean:
	cd classic && make clean
	cd advanced && make clean
	cd error && make clean
	cd ansi-care && make clean
	cd robust && make clean
	cd g++ && make clean 
    
