all:
	cd classic && make
	cd advanced && make
	cd error && make
	cd ansi-care && make

	cd debug && make
	cd robust && make	
clean:
	cd classic && make clean
	cd advanced && make clean
	cd error && make clean
	cd ansi-care && make clean

	cd debug && make clean
	cd robust && make clean     
