#!/bin/sh
#
#  $Id$
#
#  Credits script. 
#
#  Copyright (c) 98,99,00,2001 <all@antifork.org>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#


dpath=.
info=INFO
version=VERSION
confguess=config.guess
PROGRAM="program" 
AUTHOR="author"
MAIL="root@localhost"
VERSION="version"

if [ -f $dpath/$info ];
	then
	PROGRAM="`cat $info | awk '{print $1}'`"
	AUTHOR="`cat $info | awk '{print $2 " " $3}'`"
	MAIL="`cat $info | awk '{print $4}'`"
	fi
if [ -f $dpath/$version ];
	then
	VERSION="`cat $version`"
	fi

if [ -f $dpath/$confguess ];
	then
	MACHINE="`$dpath/$confguess`"
	fi
echo  
echo  "%"
echo  "% making program: $PROGRAM $VERSION "
echo  "% machine type  : $MACHINE" 
echo  "%"
echo  "% Copyright (c) 98,99,00,01,02,2003 $AUTHOR $MAIL"
echo  "%"
echo  "% Before reporting a bug, please try to reproduce it."
echo  "%"
echo 
