#!/bin/sh
#
#  $Id$
#
#  makelocale script. 
#
#  Copyright (c) 1998, 1999,2000 <all@antifork.org>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

CG=./config.guess
VE=VERSION

test -x $CG || { echo "config.guess: file not found" ; exit 0; } 
test -f $VE || { echo "VERSION: file not found" ; exit 0; } 

case "$1" in
    ""|help|-h|--help)
    echo "Usage: makelocal <header.h> <prg>"
    exit 1
    ;;
    *)
    echo "making $1"
    rm -f $1
    echo "#ifndef APG_LOCALE_H" > $1
    echo "#define APG_LOCALE_H" >> $1
    sed -e 's/.*/#define VERSION "&"/' $VE >> $1
    $CG | sed -e 's/.*/#define CPU_MFR_OPSYS "&"/' >> $1
    echo $2/apg/apg.db | sed -e 's/.*/#define APG_DB_FILE "&"/' >> $1
    echo $2/apg/apg.rules | sed -e 's/.*/#define APG_AUTORULES "&"/' >> $1
    echo "#endif /* APG_LOCALE_H */" >> $1
    ;;

esac
exit 0
