#!/bin/sh

echo "Generating test file..."
cp test.basic test

i=1
while [ $i != 16 ] 
  do
  cp  test test.tmp
  cat test >> test.tmp
  mv test.tmp test
  echo "factor amp = 2^($i)"
  i=$((i+1))

 done

